# Generated by Django 2.2 on 2021-01-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20210118_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='mail@yash.django', max_length=255, unique=True),
        ),
    ]
