# Generated by Django 2.2 on 2021-01-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20210118_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='mail@where.com', max_length=255, unique=True),
        ),
    ]
