# Generated by Django 2.2 on 2021-01-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20210118_0542'),
    ]

    operations = [
    ]
